version: '3.8'

services:
  db:
    container_name: drfv2
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=mbr-mbr-sagor
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=drfv2
    ports:
      - 5433:5432
  django:
    build: .
    container_name: drfbackend
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - pgbd
      - radis
  celery:
    build: .
    command: celery -A core worker -l INFO
    volumes:
      - /app
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - django
      - radis
  pgbd:
    image: postgres
    container_name: pgbd
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/usr/local/bin/postgres
  radis:
    image: "redis:alpine"
volumes:
  pgdata:
